// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import Header from "@/components/layout/Header";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Providers เป็น client component ที่จะตั้ง --site-top-offset อัตโนมัติ */}
        <Providers>
          {/* Header / Navbar ถูก render ใน Providers (client) */}
          <Header />
          <Navbar />

          {/* เนื้อหาหลัก — เว้นช่องด้านบนด้วย CSS variable */}
          <div style={{ paddingTop: "var(--site-top-offset, 112px)" }}>
            {children}
            {/* Footer ถ้าต้องการให้ footer อยู่ในทุกหน้า ให้แสดงที่นี่ */}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
